### ISSUE TITLE
556 warn yunbaoim@1.0.0 No repository field. 557 verbose stack Error: ENOENT: no such file or directory, access '/data/wwwroot/Live22/node_modules/after' 558 verbose cwd /data/wwwroot/Live22 559 verbose Linux 4.9.0-6-amd64 560 verbose argv "/root/.nvm/versions/node/v9.2.0/bin/node" "/root/.nvm/versions/node/v9.2.0/bin/npm" "remove" "chinese-random-name" 561 verbose node v9.2.0 562 verbose npm  v6.0.1 563 error path /data/wwwroot/Live22/node_modules/after 564 error code ENOENT 565 error errno -2 566 error syscall access 567 error enoent ENOENT: no such file or directory, access '/data/wwwroot/Live22/node_modules/after' 568 error enoent This is related to npm not being able to find a file. 569 verbose exit [ -2, true ]

### ISSUE THREAD

**Issue by xt233** [XadillaX/chinese-random-name#3]
556 warn yunbaoim@1.0.0 No repository field.
557 verbose stack Error: ENOENT: no such file or directory, access '/data/wwwroot/Live22/node_modules/after'
558 verbose cwd /data/wwwroot/Live22
559 verbose Linux 4.9.0-6-amd64
560 verbose argv "/root/.nvm/versions/node/v9.2.0/bin/node" "/root/.nvm/versions/node/v9.2.0/bin/npm" "remove" "chinese-random-name"
561 verbose node v9.2.0
562 verbose npm  v6.0.1
563 error path /data/wwwroot/Live22/node_modules/after
564 error code ENOENT
565 error errno -2
566 error syscall access
567 error enoent ENOENT: no such file or directory, access '/data/wwwroot/Live22/node_modules/after'
568 error enoent This is related to npm not being able to find a file.
569 verbose exit [ -2, true ]

**Comment by XadillaX** [comment]
没明白你要问什么
