### ISSUE TITLE
无法通过terser 导致构建失败！

### ISSUE THREAD

**Issue by caryhgq** [XadillaX/chinese-random-name#6]
项目使用vue-cli 构建，添加本项目后导致 build 失败！追其原因，webpack 构建时使用了terser ，/dict/n.js的文件导致 terser 报错，最终导致构建失败！

![image](https://user-images.githubusercontent.com/6456736/59894007-9a901700-9411-11e9-87f3-f6c999f1c012.png)

 npx terser --compress --mangle -- ./dict/n.js
![image](https://user-images.githubusercontent.com/6456736/59894336-d081cb00-9412-11e9-95f8-0cc232f58315.png)

**Comment by XadillaX** [comment]
感觉应该是给 terser 提 Issue 更合适吧？

**Comment by vsTianhao** [comment]
和terser没关系，我没用一样Maximum call stack size exceeded，因为你这个dict\n.js有点大，256kb要一直塞内存里面

**Comment by vsTianhao** [comment]
加上`--max_old_space_size=4095`就好了
